export const SHOWDIFFICULTY = 'SHOWDIFFICULTY';
export const CREATE_MAP = 'CREATE_MAP';
export const SHOW_POPUP = 'SHOW_POPUP'
export const UPDATE_DIFFICULTIES = 'UPDATE_DIFFICULTIES'
export const CHANGE_DIFFICULTY = 'CHANGE_DIFFICULTY'
export const SETBGMACTION = 'SETBGMACTION'